all:
  hosts:
    node1:
      ansible_host: 192.168.230.3
      ip: 192.168.230.3
      access_ip: 192.168.230.3
      ansible_ssh_private_key_file: /root/mastersKey
    node2:
      ansible_host: 192.168.228.10
      ip: 192.168.228.10
      access_ip: 192.168.228.10
      ansible_ssh_private_key_file: /root/workersKey
    node3:
      ansible_host: 192.168.228.11
      ip: 192.168.228.11
      access_ip: 192.168.228.11
      ansible_ssh_private_key_file: /root/workersKey
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2: 
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
